### ISSUE TITLE
some UI is not right in firefox (51.0.1, osx 10.11.6)

### ISSUE THREAD

**Issue by kimkit** [pantsel/konga#118]
![snip20171018_2](https://user-images.githubusercontent.com/1448791/31696987-59d3279a-b3e7-11e7-9e6e-e6eeea533139.png)
![snip20171018_3](https://user-images.githubusercontent.com/1448791/31696988-5a0394fc-b3e7-11e7-8143-1246b92825bb.png)

**Comment by jeremyjpj0916** [comment]
I too noticed some elements to be out of alignment from where we naturally click in chrome/ie/ff versions I run. Not a huge issue but something to consider anyways.

**Comment by pantsel** [comment]
Thanks for the pointer. I'll get it fixed on the next release.

**Comment by pantsel** [comment]
Fixed on latest release

**Comment by kimkit** [comment]
thanks

**Comment by kimkit** [comment]
not fixed.

![_2017-11-05t23-14-51 446z](https://user-images.githubusercontent.com/1448791/32420255-3eec712c-c2c2-11e7-81f4-e72addc2dac0.png)

![_2017-11-05t23-15-47 572z](https://user-images.githubusercontent.com/1448791/32420261-57205e48-c2c2-11e7-94da-3715ab5c7148.png)
