### ISSUE TITLE
When running on relative path the frontend calls /socket.io in infinite loop

### ISSUE THREAD

**Issue by bakstad** [pantsel/konga#27]
Relative paths seems really close to work now, but using the latest dev branch I get tons of these errors when opening the frontend. In `sails.io.js` there seem to be a setting `opts.path=opts.path||"/socket.io"`, but I'm not sure where to configure `opts.path`.

```
Error: [$rootScope:infdig] 10 $digest() iterations reached. Aborting!
Watchers fired in the last 5 iterations: []
http://errors.angularjs.org/1.5.11/$rootScope/infdig?p0=10&p1=%5B%5D
    at vendors.min.js:3
    at h.$digest (vendors.min.js:6)
    at h.$apply (vendors.min.js:6)
    at vendors.min.js:6
    at o (vendors.min.js:4)
    at vendors.min.js:4
(anonymous) @ vendors.min.js:5
(anonymous) @ vendors.min.js:5
$apply @ vendors.min.js:6
(anonymous) @ vendors.min.js:6
o @ vendors.min.js:4
(anonymous) @ vendors.min.js:4
```

The URL it tries to call is "/socket.io", instead of a relative path. 

```
http://MY_URL.com/socket.io/?__sails_io_sdk_version=0.11.0&__sails_io_sdk_platform=browser&__sails_io_sdk_language=javascript&EIO=3&transport=polling&t=1488279833822-5
```

In my case the correct URL would be:
```
http://MY_URL.com/konga-backend/socket.io/?__sails_io_sdk_version=0.11.0&__sails_io_sdk_platform=browser&__sails_io_sdk_language=javascript&EIO=3&transport=polling&t=1488279833822-5
```

**Comment by pantsel** [comment]
Check the new release. This issue should be fixed

**Comment by bakstad** [comment]
Hi,

The problem is still there.

What I see when using relative paths:

* Same as described above, the socket.io endpoint is called on the web root.
* `header.html`, `footer.html` and `index.html` is assumed to be on the webroot. Request URL: `http://MY_URL.com/js/core/layout/partials/header.html`, not `http://MY_URL.com/konga/js/core/layout/partials/header.html`

Otherwise great work on 0.5.x!

**Comment by pantsel** [comment]
OK,
I'll dig into that later today. Thanks for the feedback!

**Comment by pantsel** [comment]
@bakstad ,
I haven't tested it on an actual relative path, but I think this change in <code>/views/layout.ejs</code> will suffice
<pre>
<script src="/js/dependencies/sails.io.js"></script>
<script type="text/javascript">
      io.sails.url = window.location.protocol + "//" + window.location.host + window.location.pathname;
</script>
</pre>

Header and footer is loaded relatively.

Waiting for feedback and thanks again for your contribution!

**Comment by pantsel** [comment]
Yes! I missed that. It should be <code><script src="js/dependencies/sails.io.js"></script></code>

**Comment by bakstad** [comment]
I still see the same problem :/ Also it seems that calls to the backend also assume webroot with `/kong/status` for example.

**Comment by pantsel** [comment]
OK, I need to dig deeper into this. I was hoping it was a simple assets loading issue. 
I'll get back to you when I have news.

**Comment by RoosDaniel** [comment]
Any news on this? Sitting on the same error.

**Comment by pantsel** [comment]
Issue fixed in [0.7.0](https://github.com/pantsel/konga/releases/tag/0.7.0)
