### ISSUE TITLE
save upstream Passive health checks failed

### ISSUE THREAD

**Issue by lclin412** [pantsel/konga#438]
When using konga to configure the passive check policy of upstream, the healthchecks.passive.unhealthy.http_failures field enters the integer when the click is saved, js reports an error (error content: schema violation (healthchecks.passive: {↵ unhealthy = {↵ http_failures = "expected An integer"↵ }↵})). 

I found out through the packet capture that the field in the data section of the submitted healthchecks.passive.unhealthy.http_failures has become a string, and other fields have no such problem.

Konga version: 0.14.03

Thank you for your help..

**Comment by pantsel** [comment]
@lclin412 , you could try the `next` branch of Konga or if you're using containers `pantsel/konga:next`.
It has all the changes and fixes that will be introduced to the upcoming version.

**Comment by lclin412** [comment]
With the next branch, the problem has been solved, thank you for your help.

**Comment by DennisSchuenemann** [comment]
Hello, we're using Konga in Docker v0.14.4-rc2 via container using `pantsel/konga:next`, but we still have this problem.
