### ISSUE TITLE
[Error (E_UNKNOWN) Encountered an unexpected error] Details: error: invalid input syntax for integer: "NaN

### ISSUE THREAD

**Issue by Hupeli** [pantsel/konga#474]
rawStack: 'error: invalid input syntax for integer: "NaN"\n' +
    '    at Connection.parseE (node_modules/sails-postgresql/node_modules/pg/lib/connection.js:539:11)\n' +
    '    at Connection.parseMessage (node_modules/sails-postgresql/node_modules/pg/lib/connection.js:366:17)\n' +
    '    at Socket.<anonymous> (node_modules/sails-postgresql/node_modules/pg/lib/connection.js:105:22)\n' +
    '    at Socket.emit (events.js:210:5)\n' +
    '    at Socket.EventEmitter.emit (domain.js:476:20)\n' +
    '    at addChunk (_stream_readable.js:308:12)\n' +
    '    at readableAddChunk (_stream_readable.js:289:11)\n' +
    '    at Socket.Readable.push (_stream_readable.js:223:10)\n' +
    '    at TCP.onStreamRead (internal/stream_base_commons.js:182:23)',
  details: 'Details:  error: invalid input syntax for integer: "NaN"\n',
  model: undefined

**Comment by LKI** [comment]
same issue. I found this bug under `NO_AUTH`.

Fixed after remove `NO_AUTH`

**Comment by pantsel** [comment]
@LKI , at what point using the `NO_AUTH` setting did you encounter that bug? Can you please tell me how to reproduce?

**Comment by LKI** [comment]
@pantsel I use kubernetes to create a konga deployment. Reproduce steps are here:

- use `NO_AUTH` env to create a new konga deployment
- when creating first connection, dashboard will pop a `Invalid input syntax for integer`
- remove `NO_AUTH` env, apply and restart the deployment
- now it's ok to create connections

Sample k8s yml:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: konga
  namespace: konga
spec:
  selector:
    matchLabels:
      app: konga
  replicas: 1
  template:
    metadata:
      labels:
        app: konga
    spec:
      restartPolicy: Always
      initContainers:
        - name: konga-init
          image: pantsel/konga:0.14.5
          command: ["node", "bin/konga.js", "prepare", "--adapter", "postgres", "--uri", "postgresql://konga@konga:5432/konga"]
      containers:
        - name: konga
          image: pantsel/konga:0.14.5
          env:
            - name: DB_ADAPTER
              value: postgres
            - name: DB_HOST
              value: konga
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: konga
            - name: TOKEN_SECRET
              value: konga
            - name: DB_DATABASE
              value: konga
            - name: NODE_ENV
              value: production
            - name: NO_AUTH
              value: "true"
          resources:
          ports:
            - containerPort: 1337
```

**Comment by pantsel** [comment]
@LKI ,

please try Konga [0.14.6](https://github.com/pantsel/konga/releases/tag/0.14.6).
I've just released a patch.

**Comment by LKI** [comment]
@pantsel OK, I'll try

**Comment by LKI** [comment]
@pantsel same issue still, screenshot is here:

![image](https://user-images.githubusercontent.com/3286092/67144556-39d2f700-f2aa-11e9-814a-8b79c53de6b1.png)

trace:
```
"error: invalid input syntax for integer: "NaN"
    at Connection.parseE (/app/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:539:11)
    at Connection.parseMessage (/app/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:366:17)
    at Socket.<anonymous> (/app/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:105:22)
    at Socket.emit (events.js:198:13)
    at Socket.EventEmitter.emit (domain.js:448:20)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)"
```

**Comment by pantsel** [comment]
@LKI , ok found the issue. 

Just patched another update on v0.14.7

**Comment by LKI** [comment]
@pantsel It's fixed!
Thanks a lot for such rapid contribution! 🌹
