### ISSUE TITLE
Blank value for optional fields results in empty array in config

### ISSUE THREAD

**Issue by ali-sattari** [pantsel/konga#54]
Hi,

I came across this while trying to config statsd plugin for Kong through Konga dashboard.
Leaving the `metrics` field blank and results in following config:

```
{
  "api_id": "...",
  "id": "...",
  "created_at": 1493836410000,
  "enabled": true,
  "name": "statsd",
  "config": {
    "host": "127.0.0.1",
    "metrics": {},
    "timeout": 10000,
    "port": 8125
  }
}
```

While creating a plugin using curl and Kong's admin API without specifying any `metric` results in this config:

```
{
  "api_id": "...",
  "id": "...",
  "name": "statsd",
  "enabled": true,
  "created_at": 1493836153000,
  "config": {
    "host": "127.0.0.1",
    "timeout": 10000,
    "metrics": [
      "request_count",
      "latency",
      "request_size",
      "status_count",
      "response_size",
      "unique_users",
      "request_per_user",
      "upstream_latency"
    ],
    "port": 8125
  }
}
```

Needless to say that manually including all items (in this case metric items) in Konga interface would result in correct configuration being set.

I think the expected behavior should be to leave out optional blank fields out of API call to Kong's admin.

**Comment by pantsel** [comment]
Hi @ali-sattari , the issue is addressed in the new release of Konga [v0.6.7](https://github.com/pantsel/konga/releases/tag/0.6.7).

Please confirm the fix.

Thank you for the feedback!

**Comment by ali-sattari** [comment]
I tried docker image for v0.6.7 and replicated the issue.
The problem remains unchanged and leaving optional params empty results in empty array in config.

**Comment by pantsel** [comment]
@ali-sattari , can you please point to me the steps you took? Which plugin did you added leaving default fields empty?

**Comment by ali-sattari** [comment]
@pantsel I tried to set `statsd` plugin for both a specific API and all APIs. I add the plugin, leave all the fields with default value (and the `metrics` field empty) and save. This results in a config which I have provided in the original post.
BUt by calling Kong API using curl and not mentioning `metrics` field, it auto fills all available items.

**Comment by pantsel** [comment]
@ali-sattari , I can't seem to be able to reproduce this issue with Konga 0.6.7 and  Kong v0.10.0 & v0.10.2. What version of Kong are you using?

**Comment by ali-sattari** [comment]
@pantsel I am using Kong v0.10.1 with Postgres data store.

**Comment by gtrias** [comment]
I'm having issues with plugin arrays as well

konga version: 0.6.8
kong version: 0.10.2

It seems array values are saved as object in Admin API call terms.

The next curl call is working well:

```
curl -X PATCH \
  http://my-kong-admin/apis/77ea9554-dcc6-4151-8894-eb59821b55fb/plugins/6a1334e7-711e-47fa-abb1-f83633968f8a \
  -H 'authorization: Basic xxxxxxx==' \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/json' \
  -d '{
"config": {
	"uri_param_names": [
		"apikey"
	],
	"path_whitelist": [
		"/topics"
	]
}
}'
```
But trying this settings from konga sets this config values to empty object:

```
    "uri_param_names": {},
```

**Comment by pantsel** [comment]
@ali-sattari , @gtrias . Does this issue persists with the latest commits?

**Comment by gtrias** [comment]
@pantsel no sorry. I was missing to press enter to submit the value :smile:

**Comment by pantsel** [comment]
Closing this issue as resolved. Feel free to reopen if needed.
